import React, { useCallback, useEffect, useRef, useState } from "react";
import { ModalWindow } from "./ModalWindow";
import { Switch } from "../components/Switch";
import { InputField } from "../components/InputField";
import clientController, { COLORS } from "../application/ClientController";
import serverController from "../application/ServerController";
import { TextPreview } from "../components/TextPreview";
import { DynamicList } from "../components/DynamicList";


export const ProcessThemeModal = ({closeCallback = () => {}}) => {
    const [formState, SetForm] = useState(0);
    const [onButton, setOnButton] = useState(() => () => {return false});

    let currentForm = null;
    switch(formState){
        case 1: currentForm = <IntegrationForm setButtonCallback={setOnButton}/>; break;
        case 0: currentForm = <ThemeForm setButtonCallback={setOnButton}/>; break;
    }

    return(
        <ModalWindow title="Create theme" closeCallback={closeCallback} defaultButton={{
            function: onButton,
            title: 'Create',
            isActive: true,
            type: 'submit',
        }}
        size={1}>
            <Switch title={'Choose form'} values={[
                {val: 0, prev: 'Theme'}, {val: 1, prev: 'Integration', buttonStyles:{width: 'auto'}}
            ]} current={0} callback={SetForm}/>
            
            {currentForm}
        </ModalWindow>
    )
}

const ThemeForm = ({setButtonCallback = () => {}}) => {
    const [data, setData] = useState({
        title: null, maxPoints: null, isAutoGenerated: false
    });

    const UpdateData = useCallback((property, value) => {
        setData(prev => {
            if(!Object.hasOwn(prev, property)) return prev;
            return {...prev, [property]: value};
        });
    });

    useEffect(() => {
        setButtonCallback(() => async () => {
            let info;

            await new Promise((resolve) => {
                setData((prev) => {
                    info = {...prev};
                    resolve();
                    return prev;
                });
            });
            

            const {title, maxPoints} = info;
            if(title === null || maxPoints === null) return false;
            const result = serverController.createTheme(info, () => {
                clientController.triggerEvent('show-tip', ['Wrong!', clientController.getColorSetting(2, 'red')]);
            });

            if(result) clientController.triggerEvent('show-tip', ['Success!', clientController.getColorSetting(2, 'green')]);
            return result;
        });
    }, []);

    return(
        <form >
            <InputField styles={{
                left: '5%', width: '90%'
            }} defaultValue={'Title'} max={15} min={3} onValueChange={(val, status) => {
                if(status == 2) UpdateData('title', val);
                else UpdateData('title', null)
            }}/>
            <InputField styles={{
                left: '5%', width: '90%'
            }} typeID={2} pattern="number"
            defaultValue={'Max points'} onValueChange={(val, status) => {
                if(status == 2) UpdateData('maxPoints', val);
                else UpdateData('maxPoints', null);
            }}
            contextValidate={async (val) => {
                if(Number.isNaN(+val)) {
                    clientController.triggerEvent('show-tip', ['Max points must be in number', clientController.getColorSetting(2, 'yellow')]);
                    return false;
                }
                const limit_max = 50000;
                const limit_min = 1000;
                if(+val > limit_max){
                    clientController.triggerEvent('show-tip', ['The number of points should not be more than ' + limit_max, clientController.getColorSetting(2, 'yellow')]);
                    return false;
                }
                if(+val < limit_min){
                    clientController.triggerEvent('show-tip', ['The number of points should be more than ' + limit_min, clientController.getColorSetting(2, 'yellow')]);
                    return false;
                }
                
                return true;
            }}
            />
            <Switch title={'Autogeneration'} values={[
                {val: false, prev: 'False', buttonStyles: {backgroundColor: clientController.getColorSetting(2, 'red')}}, 
                {val: true, prev: 'True', buttonStyles: {backgroundColor: clientController.getColorSetting(2, 'green')}}
            ]} current={0} callback={(val) => UpdateData('isAutoGenerated', val)}/>
        </form>
    );
}

const IntegrationForm = ({setButtonCallback = () => {}}) => {
    const [data, setData] = useState({
        name: null, service: null, method: 'GET', params: [], headers: []
    });
    const scrollRefs = {params: useRef(null), headers: useRef(null)};

    const UpdateData = useCallback(async (property, value) => {
        await new Promise((resolve) => {
            setData(prev => {
                if(!Object.hasOwn(prev, property)) return prev;
                resolve();
                return {...prev, [property]: value};
            });
        });
        
        switch(property){
            case 'params':
            case 'headers':                 
                scrollRefs[property].current.scrollIntoView({behavior: "smooth"});
                break;
        }
    }, []);

    useEffect(() => {
        setButtonCallback(() => async () => {
            let info;

            await new Promise((resolve) => {
                setData((prev) => {
                    info = {...prev};
                    resolve();
                    return prev;
                });
            });
            
            const {name, service} = info;
            if(name ===  null || service === null) return false;
            const result = serverController.createIntegration(info, (status, message) => {
                clientController.triggerEvent('show-tip', ['Wrong', clientController.getColorSetting(2, 'red')]);
            });
            
            if(result) clientController.triggerEvent('show-tip', ['Success!', clientController.getColorSetting(2, 'green')]);
            return result;
        });
    }, []);

    const validate = useCallback((val, property) => {
        console.log(val, property);
        const parts = val.split(':');
        if(parts.length !== 2) return false;
        if(data[property].filter(text => text === val).length > 0) return false;
        return true;
    },[])

    return(
        <form className="IntegrationForm">
            <TextPreview text={serverController.userData.chosenTheme.title} wrapStyles={{width: '90%', left: '5%'}}/>
            <InputField styles={{
                left: '5%', width: '90%'
            }} defaultValue={'Name'} max={15} min={3} onValueChange={(val, status) => {
                if(status == 2) UpdateData('name', val);
                else UpdateData('name', null)
            }}/>
            <InputField styles={{
                left: '5%', width: '90%'
            }}
            defaultValue={'Service: https://example.com/endpoint'} onValueChange={(val, status) => {
                if(status == 2) UpdateData('service', val);
                else UpdateData('service', null);
            }} max={250}/>
            <Switch title={'Method'} values={[
                {val: 'GET', prev: 'Get',}, 
                {val: 'POST', prev: 'Post',}
            ]} current={0} callback={(val) => UpdateData('method', val)}/>
            <DynamicList ref={scrollRefs.params} defaultValue="Paramethers: Key:Value" min={3} max={500} verify={(val) => validate(val, 'params')}
            onUpdate={(val) => UpdateData('params', val)}/>
            <DynamicList ref={scrollRefs.headers} defaultValue="Headers: Key:Value" min={3} max={500} verify={(val) => validate(val, 'headers')}
            onUpdate={(val) => UpdateData('headers', val)}/>
        </form>
    );
}
