import React, { useCallback, useEffect, useRef, useState } from "react";
import { ModalWindow } from "./ModalWindow";
import { Switch } from "../components/Switch";
import { NewsBlock } from "../components/NewsBlock";
import { InputField } from "../components/InputField";
import clientController, { COLORS } from "../application/ClientController";
import serverController from "../application/ServerController";
import { DefaultButton } from "../components/DefaultButton";
import PlusIcon from "../assets/icons/Plus.svg"
import { TextPreview } from "../components/TextPreview";


export const ProcessThemeModal = ({closeCallback = () => {}}) => {
    const [formState, SetForm] = useState(0);
    const [onButton, setOnButton] = useState(() => () => {return false});

    let currentForm = null;
    switch(formState){
        case 1: currentForm = <IntegrationForm />; break;
        case 0: currentForm = <ThemeForm setButtonCallback={setOnButton}/>; break;
    }

    return(
        <ModalWindow title="Create theme" closeCallback={closeCallback} defaultButton={{
            function: onButton,
            title: 'Create',
            isActive: true,
            type: 'submit',
        }}
        size={1}>
            <Switch title={'Choose form'} values={[
                {val: 0, prev: 'Theme'}, {val: 1, prev: 'Integration'}
            ]} current={0} callback={SetForm}/>
            
            {currentForm}
        </ModalWindow>
    )
}

const ThemeForm = ({setButtonCallback = () => {}}) => {
    const [data, setData] = useState({
        title: null, maxPoints: null, isAutoGenerated: false, data: undefined
    });

    const UpdateData = useCallback((property, value) => {
        setData(prev => {
            if(!Object.hasOwn(prev, property)) return prev;
            return {...prev, [property]: value};
        });
    });


    let additionalData
    if(data.isAutoGenerated){
        additionalData = <InputField styles={{
            left: '5%', width: '90%'
        }}
        defaultValue={'Enter data separated by commas: D1, D2, D3'} max={10000} min={0}
            onValueChange={(val) => UpdateData('data', val)} 
        />
    }

    useEffect(() => {
        setButtonCallback(() => async () => {
            let info;

            var promise = await new Promise((resolve) => {
                setData((prev) => {
                    info = {...prev};
                    resolve();
                    return prev;
                });
            });
            
            console.log(info);

            const {title, maxPoints} = info;
            if(title === null || maxPoints === null) return false;
            // serverController.
            return true;
        });
    }, []);

    return(
        <form >
            <InputField styles={{
                left: '5%', width: '90%'
            }} defaultValue={'Title'} max={15} min={3} onValueChange={(val, status) => {
                if(status == 2) UpdateData('title', val);
                else UpdateData('title', null)
            }}/>
            <InputField styles={{
                left: '5%', width: '90%'
            }} typeID={2}
            defaultValue={'Max points'} onValueChange={(val, status) => {
                if(status == 2) UpdateData('maxPoints', val);
                else UpdateData('maxPoints', null);
            }}
            contextValidate={async (val) => {
                if(Number.isNaN(+val)) {
                    clientController.triggerEvent('show-tip', ['Max points must be in number', clientController.getColorSetting(2, 'yellow')]);
                    return false;
                }
                const limit_max = 50000;
                const limit_min = 1000;
                if(+val > limit_max){
                    clientController.triggerEvent('show-tip', ['The number of points should not be more than ' + limit_max, clientController.getColorSetting(2, 'yellow')]);
                    return false;
                }
                if(+val < limit_min){
                    clientController.triggerEvent('show-tip', ['The number of points should be more than ' + limit_min, clientController.getColorSetting(2, 'yellow')]);
                    return false;
                }
                
                return true;
            }}
            />
            <Switch title={'Autogeneration'} values={[
                {val: false, prev: 'False', buttonStyles: {backgroundColor: clientController.getColorSetting(2, 'red')}}, 
                {val: true, prev: 'True', buttonStyles: {backgroundColor: clientController.getColorSetting(2, 'green')}}
            ]} current={0} callback={(val) => UpdateData('isAutoGenerated', val)}/>

            {additionalData}
        </form>
    );
}

const IntegrationForm = ({}) => {
    const [data, setData] = useState({
        name: null, service: null, key: null, method: 'GET', params: []
    });
    const [paramether, setParam] = useState(null); 
    const clearRef = useRef(undefined);
    const scrollRef = useRef(undefined);

    const UpdateData = useCallback((property, value) => {
        setData(prev => {
            if(!Object.hasOwn(prev, property)) return prev;

            return {...prev, [property]: value};
        });
    });

    return(
        <form className="IntegrationForm">
            <TextPreview text={serverController.userData.chosenTheme.title} wrapStyles={{width: '90%', left: '5%'}}/>
            <InputField styles={{
                left: '5%', width: '90%'
            }} defaultValue={'Name'} max={15} min={3} onValueChange={(val, status) => {
                if(status == 2) UpdateData('name', val);
                else UpdateData('name', null)
            }}/>
            <InputField styles={{
                left: '5%', width: '90%'
            }}
            defaultValue={'Service: https://example.com/endpoint'} onValueChange={(val, status) => {
                if(status == 2) UpdateData('service', val);
                else UpdateData('service', null);
            }} />
            <InputField styles={{
                left: '5%', width: '90%'
            }}
            defaultValue={'key'} onValueChange={(val, status) => {
                if(status == 2) UpdateData('key', val);
                else UpdateData('key', null);
            }}/>
            <Switch title={'Method'} values={[
                {val: 'GET', prev: 'Get',}, 
                {val: 'POST', prev: 'Post',}
            ]} current={0} callback={(val) => UpdateData('method', val)}/>
            {
                data.params.map(val => (
                    <div style={{
                        display: 'flex',
                        position: 'relative',
                        marginBottom: '5%',
                        left: '5%', 
                        width: '90%',
                    }}>
                        <TextPreview text={val} key={val} wrapStyles={{width: '80%', marginBottom: '0%'}}/>
                        <DefaultButton text={<PlusIcon className={'XIcon'}/>} onClick={(ev) => {
                            ev.preventDefault();
                            const params = data.params.filter((text) => text !== val);

                            UpdateData('params', params);
                        }}
                        styles={{
                            height: '5.5vh',
                            width: '5.5vh',
                            margin: '0 auto',
                            position: 'relative',
                            backgroundColor: clientController.getColorSettingDefault(COLORS.functionalA),
                        }}/>
                    </div>

                ))
            }
            <div style={{
                    display: 'flex',
                    position: 'relative',
                    marginBottom: '5%',
                    left: '5%', 
                    width: '90%',
                }}>
                <InputField defaultValue={'key:value'} max={25} min={1} onValueChange={(val, status) => {
                    if(status === 2) setParam(val);
                    else setParam(null);
                }}  clearFunctionRef={clearRef} contextValidate={(val) => {
                    const parts = val.split(':');
                    console.log(parts.length);
                    if(parts.length !== 2) return false;
                    if(data.params.filter(text => text === val).length > 0) return false;
                    return true;
                }}
                    pattern="question" styles={{width: '80%', marginBottom: '1%'}} />
                <DefaultButton text={<PlusIcon />} onClick={(ev) => {
                    ev.preventDefault();
                    if(paramether === null) return;

                    const params = [...data.params, paramether]; 
                    setParam(null);
                    UpdateData('params', params);
                    clearRef.current();

                    scrollRef.current && scrollRef.current.scroll({behavior: "smooth"});
                }}
                    styles={{
                        height: '5.5vh',
                        width: '5.5vh',
                        margin: '0 auto',
                        position: 'relative',
                        backgroundColor: clientController.getColorSettingDefault(COLORS.functionalA),
                    }}>
                </DefaultButton>
            </div>
        </form>
    );
}